"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "./metadata";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My ..</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
